apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h7a2dopsh-java-springboot
  janus-idp.io/tekton: h7a2dopsh-java-springboot
  backstage.io/kubernetes-id: h7a2dopsh-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h7a2dopsh-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
